// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIXZmvUChFpZQHADqBKhEt4DGgL-2R-0w',
    appId: '1:198619291778:web:0fbdd404db10bd7a62d49b',
    messagingSenderId: '198619291778',
    projectId: 'sarapero-1e45e4',
    authDomain: 'sarapero-1e45e4.firebaseapp.com',
    databaseURL: 'https://sarapero-1e45e4-default-rtdb.firebaseio.com',
    storageBucket: 'sarapero-1e45e4.appspot.com',
    measurementId: 'G-SVTREMSLPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNS97-oMELMfau87gyPs-bGMwHnpA-ERE',
    appId: '1:198619291778:android:6f6dfab56919330a62d49b',
    messagingSenderId: '198619291778',
    projectId: 'sarapero-1e45e4',
    databaseURL: 'https://sarapero-1e45e4-default-rtdb.firebaseio.com',
    storageBucket: 'sarapero-1e45e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8FrlG5bJi0a07i0DgTRBYRrt84G2ReeI',
    appId: '1:198619291778:ios:4bb4f70d13237e6e62d49b',
    messagingSenderId: '198619291778',
    projectId: 'sarapero-1e45e4',
    databaseURL: 'https://sarapero-1e45e4-default-rtdb.firebaseio.com',
    storageBucket: 'sarapero-1e45e4.appspot.com',
    iosClientId: '198619291778-k0m6s5p8amud7b68to4r1262b2enfppc.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
